version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"
    networks:
      - net

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: announcement
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    networks:
      - net

  authapp:
    build:
      context: .
      dockerfile: Dockerfile_auth
    ports:
      - "${AUTH_APP_PORT}:${AUTH_APP_PORT}"
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    depends_on:
      - redis
      - postgres
    env_file:
      .env
    networks:
      - net

  marketapp:
    build:
      context: .
      dockerfile: Dockerfile_market
    ports:
      - "${MARKET_APP_PORT}:${MARKET_APP_PORT}"
    depends_on:
      - redis
      - postgres
    env_file:
      .env
    networks:
      - net

networks:
  net:
    driver: bridge