version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_DOCKER_PORT}:6379"
    networks:
      - net

  authpsx:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${AUTH_PSX_PASSWORD}
      POSTGRES_USER: ${AUTH_PSX_USER}
      POSTGRES_DB: ${AUTH_PSX_DBNAME}
    volumes:
      - ./scripts/sql/auth:/docker-entrypoint-initdb.d
    ports:
      - "${AUTH_PSX_DOCKER_PORT}:5432"
    networks:
      - net

  marketpsx:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${MARKET_PSX_PASSWORD}
      POSTGRES_USER: ${MARKET_PSX_USER}
      POSTGRES_DB: ${MARKET_PSX_DBNAME}
    volumes:
      - ./scripts/sql/market:/docker-entrypoint-initdb.d
    ports:
      - "${MARKET_PSX_DOCKER_PORT}:5432"
    networks:
      - net

  authapp:
    build:
      context: .
      dockerfile: Dockerfile_auth
    ports:
      - "${AUTH_APP_PORT}:${AUTH_APP_PORT}"
      - "${AUTH_GRPC_PORT}:${AUTH_GRPC_PORT}"
    depends_on:
      - redis
      - authpsx
      - marketpsx
    env_file:
      .env
    networks:
      - net

  marketapp:
    build:
      context: .
      dockerfile: Dockerfile_market
    ports:
      - "${MARKET_APP_PORT}:${MARKET_APP_PORT}"
    depends_on:
      - redis
      - authpsx
      - marketpsx
    env_file:
      .env
    networks:
      - net

networks:
  net:
    driver: bridge