version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6378:6379"
    networks:
      - net

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: announcement
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - postgres
    networks:
      - net

networks:
  net:
    driver: bridge